[package]
name = "clay-viewer"
version = "0.0.2"
authors = ["Alexey Gerasev <alexey.gerasev@gmail.com>"]
license = "MIT/Apache-2.0"
edition = "2018"

description = "Graphical viewer for Clay - an OpenCL ray/path tracer"
homepage = "https://github.com/nthend/clay"
repository = "https://github.com/nthend/clay"
readme = "README.md"

keywords = ["ray-tracing", "path-tracing", "opencl"]
categories = ["graphics", "rendering", "multimedia"]

[dependencies]
clay-core = { git = "https://github.com/clay-rs/clay-core.git", rev = "14a3a4a1893e7658adad6b9167ed9326e0b91886" }
#clay-core = { path = "../clay-core" }

nalgebra = "0.18"
sdl2 = "0.32"
rental = "0.5.4"
